version: "3.7"

services:
#  monolith_service:
#    container_name: 'monolith_service'
#    build:
#      context: ./monolith_service/
#      dockerfile: ./docker/Dockerfile
#    ports:
#      - "8081:8081"
  order_service:
    container_name: 'order_service'
    build:
      context: ./order_service/
      dockerfile: ./docker/Dockerfile
    ports:
      - "8082:8081"
  stock_service:
    container_name: 'stock_service'
    build:
      context: ./stock_service/
      dockerfile: ./docker/Dockerfile
    ports:
      - "8083:8081"
  product_service:
    container_name: 'product_service'
    build:
      context: ./product_service/
      dockerfile: ./docker/Dockerfile
    ports:
      - "8084:8081"
  database:
    container_name: 'simply_media_database'
    image: postgres:11.2
    volumes:
        - ./docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - "5432:5432"

    environment:
      - POSTGRES_MULTIPLE_DATABASES=orders_db,monolith_db,stocks_db,products_db
      - POSTGRES_USER=username
      #- POSTGRES_DB=simplymedia
      - POSTGRES_PASSWORD=password