version: "3.7"

services:
  web:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - "8081:8081"
  database:
    container_name: 'simply_media_container'
    image: postgres:11.2
    restart: always
    ports:
      - "5432:5432"

    environment:
      - POSTGRES_USER=username
      - POSTGRES_DB=simplymedia
      - POSTGRES_PASSWORD=password